name: Build Gambit

on:
  push:
    branches: [ build-gambit ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSYS2
      uses: numworks/setup-msys2@v1
      with:
        update: true
        path-type: inherit
        msystem: MSYS

    - name: Install VC++ 2015
      run: choco install microsoft-visual-cpp-build-tools -y

    - name: Install Dependencies
      shell: cmd
      run: msys2do pacman -S --noconfirm autoconf make patch

    - name: Build Code
      shell: cmd
      run: |
        set PATH=%RUNNER_TEMP%\msys\msys64\usr\bin;%PATH%
        mkdir dist
        build-gambit.cmd
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-windows
        path: dist/

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Gambit Scheme
      run: ./build-gambit.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-linux
        path: dist/
