name: Build Gambit

on:
  push:
    branches: [ build-gambit ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSYS2
      uses: numworks/setup-msys2@v1
      with:
        update: true
        path-type: inherit

    - name: Install VC++ 2015
      run: choco install microsoft-visual-cpp-build-tools -y

    - name: Install Dependencies
      shell: cmd
      run: msys2do pacman -S --noconfirm autoconf make patch

    - name: Build Code
      shell: cmd
      run: |
        dir "C:\Program Files (x86)\Microsoft Visual C++ Build Tools\"
        set prevdir=%CD%
        call "C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools.bat" x64
        set PATH=c:\tools\msys64\usr\bin;%PATH%
        cd %prevdir%
        mkdir dist
        wget -O config.sub 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'
        wget -O config.guess 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
        patch < config.patch
        sh -c "./configure --enable-single-host --prefix=%CD:\=/%/dist CC=cl; make -j4; make install"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-windows
        path: dist/

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Gambit Scheme
      run: ./build-gambit.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-linux
        path: dist/
