name: Build Gambit

on:
  push:
    branches: [ build-gambit ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSYS2
      uses: numworks/setup-msys2@v1
      with:
        update: true
        path-type: inherit
        msystem: MSYS

    - name: Install Dependencies
      shell: cmd
      run: msys2do pacman -S --noconfirm autoconf make patch

    - name: Build Code
      shell: cmd
      run: |
        REM The initial checkout doesn't fetch tags, do that now
        REM so that bootstrapping works
        git fetch origin --tags

        REM Use the msys2 installation directly via PATH
        set PATH=%RUNNER_TEMP%\msys\msys64\usr\bin;%PATH%

        REM Run the build script
        mkdir dist
        .github\workflows\build-gambit.cmd

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-win-x64-cl
        path: dist/

    - name: Publish Release Artifact
      run: |
        # Fake a package.json to make publish-release happy
        "{}" | sc package.json
        $hash = git rev-parse --short HEAD
        Compress-Archive -Path .\dist\* -DestinationPath gambit-win-x64-cl.zip
        npx publish-release --token $env:GITHUB_TOKEN --repo gambit --owner daviwil --name latest-$hash --tag latest-$hash --notes="Automated Build" --assets gambit-win-x64-cl.zip --reuseRelease --target_commitish $env:GITHUB_SHA

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Gambit Scheme
      run: ./.github/workflows/build-gambit.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: gambit-linux
        path: dist/
